apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: vino-rico
  namespace: development
spec:
  name: vino-rico
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://clusters.dev.bayescluster.com/mlruns/1/3c7c93a9cf204fd0bfecf8e403afd666/artifacts/wine
        name: classifier
        envSecretRefName: seldon-init-container-secret
      name: default
      replicas: 1
      svcOrchSpec:
         env:
            - name: SELDON_LOG_LEVEL
              value: DEBUG
