apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: vino-rico
  namespace: staging
spec:
  name: vino-rico
  predictors:
    - componentSpecs:
       - hpaSpec:
           minReplicas: 1
           maxReplicas: 1
           metrics:
           - resource:
               name: cpu
               targetAverageUtilization: 50
             type: Resource
           - resource:
               name: memory
               targetAverageValue: 50Mi
             type: Resource
      graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://clusters.dev.bayescluster.com/mlruns/1/1ffdeaefc5b747548f4aa061f3d0e5a8/artifacts/wine
        name: classifier
        envSecretRefName: seldon-init-container-secret
      name: default
      svcOrchSpec:
         env:
           - name: SELDON_LOG_LEVEL
             value: DEBUG
