version: "3.1"

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: delcacho/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: delcacho/dask
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: delcacho/dask-notebook
    hostname: notebook
    ports:
      - "8888:8888"
      - "8000:8000"
      - "443:443"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"

  jenkins-connector:
    build:
      context: ./jenkins-connector
      dockerfile: Dockerfile
    image: delcacho/jenkins-connector
    hostname: jenkins-connector

  jenkins-agent:
    build:
      context: ./jenkins-agent
      dockerfile: Dockerfile
    image: delcacho/jenkins-agent
    hostname: jenkins-agent

  mlflow:
    build:
      context: ./mlflow-docker
      dockerfile: Dockerfile
    image: delcacho/mlflow
    hostname: mlflow

  spark:
    build:
      context: ./spark-docker
      dockerfile: Dockerfile
    image: delcacho/spark
    hostname: spark
