## Postgresql values
postgresqlUsername: "postgres"
postgresqlPassword: "pruebademlflow"
postgresqlDatabase: "mlflowdb"
service:
   port: 5432
pgHbaConfiguration: "host    all    all    0.0.0.0/0    trust\nlocal	all	all	trust"
