apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: notebook
  name: notebook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notebook
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: notebook
    spec:
      containers:
      - env:
        - name: DASK_SCHEDULER_ADDRESS
          value: '"tcp://scheduler:8786"'
        image: delcacho/dask-notebook
        imagePullPolicy: ""
        name: notebook
        ports:
        - containerPort: 8888
        - containerPort: 8000
        - containerPort: 443
        resources: {}
      hostname: notebook
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
