agent:
  image: delcacho/jenkins-agent
  tag: latest
  alwaysPullImage: true

controller:
  adminPassword: jenkins
  credentialsXmlSecret: jenkins-credentials
  secretsFilesSecret: jenkins-secrets-secret
  installPlugins:
    - kubernetes:1.29.6
    - workflow-aggregator:2.6
    - credentials-binding:1.24
    - git:4.7.1
    - workflow-job:2.40
    - pipeline-aws:1.43
    - config-autorefresh-plugin:1.0
  authorizationStrategy: |-
     <authorizationStrategy class="hudson.security.AuthorizationStrategy$Unsecured">
       <denyAnonymousReadAccess>false</denyAnonymousReadAccess>
     </authorizationStrategy>
