library(sparklyr)
library(h2o)
options(rsparkling.sparklingwater.version = '3.30.1.2-1-2.4')
options(rsparkling.sparklingwater.location = '/home/admin/sparkling-water-3.30.1.2-1-2.4')
library(rsparkling)
sc <- spark_connect('spark://spark-master-svc:7077')
hc <- H2OContext(sc)
